name: GitHub Continuous Integration

on:
  workflow_dispatch:
    inputs:
      USER:
        description: 'User to greet'
        required: true
        default: 'Scriptasaurus Rex'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Makefile
        env:
          USER: ${{ github.event.inputs.USER }}
        run: make all
