name: GitHub Continuous Integration

on:
  workflow_dispatch:
    inputs:
      POTATO:
        description: 'Potato user'
        required: true
        default: 'Potato'
      TOMATO:
        description: 'Tomato user'
        required: true
        default: 'Tomato'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Makefile
        env:
          POTATO: ${{ github.event.inputs.POTATO }}
          TOMATO: ${{ github.event.inputs.TOMATO }}
        run: make all
